version: '3'
services:

  web:
    container_name: web
    image: jwywoo26/willyou_ci_cd
    expose:
      - 8080
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    image: jwywoo26/willyou-nginx
    ports:
      - 80:80
    depends_on:
      - web