# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "feat/#57-docker-config" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up DJK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: make application-aws.yml
      run: |
        # create application-aws.yml
        cd ./src/main
        if [ ! -d "resources" ]; then
          mkdir resources
        fi
        cd ./resources

        # application-aws.yml 파일 생성하기
        touch ./application-aws.yml

        # Secrets에 저장한 값을 application-aws.yml 파일에 쓰기
        # RDS
        echo "${{ secrets.RDS }}" >> ./application-aws.yml
        # General
        echo "${{ secrets.GENERAL }}" >> ./application-aws.yml
        # S3
        echo "${{ secrets.S3 }}" >> ./application-aws.yml
        # Swagger
        echo "${{ secrets.SWAGGER }}" >> ./application-aws.yml
        # Redis
        echo "${{ secrets.REDIS }}" >> ./application-aws.yml

        # Email Send Configuration_SMTP
        echo "${{ secrets.EMAIL }}" >> ./application-aws.yml
        

      shell: bash

    - name: Build with Gradle
      run: ./gradlew bootJar

    ## 도커 이미지 빌드 후 도커허브에 push하기
    - name: web docker build and push
      run: |
        docker build -t ${{ secrets.DOCKER_REPO }} .
        docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_REPO }}
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      ## 서버에 접속하여 도커 이미지를 pull 받고 실행하기
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          sudo docker stop prod-server
          sudo docker rm prod-server
          sudo docker image rm ${{ secrets.DOCKER_REPO }}
          sudo docker pull ${{ secrets.DOCKER_REPO }}
          sudo docker run -d -p 80:8080 ${{ secrets.DOCKER_REPO }}
